const express = require('express');
const bodyparser=require('body-parser');
const cors= require('cors');
const connectDB=require('./connection');
const app= express();
app.use(bodyparser.json());
app.use(cors());
//connectDB();
//app.use(express.json({extended:false}));
//app.use('/api/userModel',require('./api/user_reg'));
const user=require('./routes/api/user_reg');
app.use('/api/user',user_reg);
const Port=process.env.Port || 3000;
app.listen(Port,()=>console.log("server started"));
