const express = require('express');
const bodyparser=require('body-parser');
const cors= require('cors');
const connectDB=require('./connection');
const app= express();
app.use(bodyparser.json());
app.use(cors());
connectDB();
app.use(express.json({extended:false}));
app.use('/api/userModel',require('./routes/api/user_reg'));
const port=process.env.PORT || 3000;
app.listen(port,()=>console.log(`server started listening on ${port}`));
